### ISSUE TITLE
A way to make a notice multilingual

### ISSUE THREAD

**Issue by mdavids** [matcornic/hugo-theme-learn#128]
theme.css contains static english words for the notices ('warning', 'note', 'tip', 'info').

It would be great if there was a way to make notices multilingual.

**Comment by magomimmo** [comment]
In my `theme-mine.css` I did as follows (for italian language):

```css
/* multilingual notice */

div.notices.warning:lang(it) p:first-child:after {
    content: 'Attenzione';
}
div.notices.note:lang(it) p:first-child:after {
    content: 'Nota';
}
div.notices.tip:lang(it) p:first-child:after {
    content: 'Suggerimento';
}
```
