### ISSUE TITLE
Timestamp embedding in URLs

### ISSUE THREAD

**Issue by eddelbuettel** [matcornic/hugo-theme-learn#193]
I am currently not deploying to Netlify but "simply" to GitHub Pages via static rendering previewing locally before commiting.  That strikes me a defensible workflow even if more docs assume one would always push to Netlify.

One downside of the current (still somewhat default) use is that something (the embedded search?) embeds the current-time since epoch in the rendered html.  So there is a lot of spurious change from commit to change.

Is there a way to turn this off?

**Comment by matalo33** [comment]
I understand the use case. You're right it's not ideal but is a nice simple approach to getting the website online.

I think you might be referring to the timestamp after the css, js, etc. files? such as `./css/hugo-theme.css?1542379156` and `./js/search.js?1542379156`

Add this under the `[params]` section of `config.toml`

```
disableAssetsBusting = true
```

**Comment by eddelbuettel** [comment]
Yes that is precisely the issue.

I added the `disableAssetsBusting = true` and re-ran, for which I use

```sh
#!/bin/bash
hugo server --destination docs --renderToDisk
```

(as `docs/` makes it even easier with GH pages) and it added the dreaded timestamps back again in updated values, ie

```
+    <link href="./css/nucleus.css?1542380680" rel="stylesheet">                           
+    <link href="./css/fontawesome-all.min.css?1542380680" rel="stylesheet">     
```

and that timestamps is indeed 'now':

```r
R> anytime::anytime(1542380680)    ## an R helper function
[1] "2018-11-16 09:04:40 CST"
R> 
```

**Comment by eddelbuettel** [comment]
And I don't see a 'reopen' button.

**Comment by matalo33** [comment]
Timestamps shouldn't get added if the option is set to true. Is the option within the `[params]` section in your config.toml?
```
[params]
  disableAssetsBusting = true
```

**Comment by eddelbuettel** [comment]
Yup.  Simply indented but that should not matter:

```toml
baseURL = "http://dspm.stat430.com"
title = "STAT430 - Data Science Programming Methods - Spring 2019"
theme = "hugo-theme-learn"

copyright = "&copy; 2018 Dirk Eddelbuettel"
enableEmoji = false

footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true

# Only use English, no multilingual support
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# code highlighting
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Languages
[languages.en]
  languageCode = "en-us"

# Outputs
[outputs]
  home = [ "HTML", "RSS", "JSON"]
  section = [ "HTML", "RSS" ]
  taxonomy = [ "HTML", "RSS" ]
  taxonomyTerm = [ "HTML", "RSS" ]

# Rendering engine
[blackfriday]
  hrefTargetBlank = true

[params]
  # Change default color scheme with a variant one
  themeVariant = "illinois"

  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true

  # no JS highlighting
  useHLJS = false

  # help with issue #193 on timestamp
  disableAssetBusting = true
```

It's pretty vanilla. I mod'ed the theme to fit school colours etc, have the other issue #187 regarding code markup and that's it.  `hugo` as the binary in Ubuntu 18.04.1, ie package version 0.40.1-1.
