### ISSUE TITLE
h5 font size property incorrect

### ISSUE THREAD

**Issue by andrew-g-za** [matcornic/hugo-theme-learn#23]
Hi there,

I see in the hugo-theme.css file the definition of h5 elements is
```css
h5 {
  font-size: 1;
  line-height: 110% !important;
  margin: 1rem 0 0.2rem 0;
}
```

This results in the h5 not being rendered correctly. Firefox's dev tools shows the property is invalid because no units have been specified.

![image](https://cloud.githubusercontent.com/assets/11553559/20592795/340bae1c-b238-11e6-8052-2fc5202d6061.png)

I think this should be changed to follow the other h2...h4 definitions that use rem units, so:

 font-size: 1**rem**;
