### ISSUE TITLE
Question: How to change tab title text

### ISSUE THREAD

**Issue by pocc** [matcornic/hugo-theme-learn#280]
### Desired Behavior

I am trying to change the text in the browser tab to stay as "Website Title". It appears that this part of the config.toml is responsible for the "Website Title" part: 

```toml
[Languages]
  [Languages.en]
  title = "Website Title"
```

### Actual Behavior

Currently it changes the text in the browser tab to "Article Title :: Website Title"

Similar to this [hugo question](https://discourse.gohugo.io/t/having-trouble-fixing-tab-title-text/11996).
