### ISSUE TITLE
Ability to use Mermaid CDN

### ISSUE THREAD

**Issue by mirisbowring** [matcornic/hugo-theme-learn#361]
Hi all,

I run into trouble using mermaid because i want some features that are not available in the current version of this theme.  
Well, I could download the latest JS File and save it to `static/mermaid/mermaid.js`.BUT I don't like the behaviour, that i have to check in a dependency into my Repository. Also the latest mermaid.min.js has a size around 1.5 MB. Every Update of the mermaid JS would cause my repository to grow.  
  
**This is why i would like to be able to use mermaid from it's CDN.**
  
**I would think about following behaviour:**  
 
Add the specific url for the mermaid.min.js to the config.toml
```toml
[params]
    mermaidURL = "https://unpkg.com/browse/mermaid@8.4.5/dist/mermaid.min.js"
```
Alternatively the version
```toml
[params]
    mermaidVersion = "8.4.5"
```
If the url / version is not specified by the user, fall back to the internal version of the theme. This will also be used if the server has no public internet access.  

This would give the user the ability to update the mermaid version much more faster than waiting for the theme to be updated. Also the user is able to minimize it's repository size since the latest version of mermaid is about 1,5 MB!

#326 wants to update the included version. But it's already outdated (see my problem description above).
