### ISSUE TITLE
Icons from content files not working

### ISSUE THREAD

**Issue by fUE4** [matcornic/hugo-theme-learn#363]
![missingIcons](https://user-images.githubusercontent.com/50083996/72509496-fb68bc00-3847-11ea-99c1-bf42956b2a2c.jpg)

What I did:
1. new Site
2. copied static, layouts and content folder from example site to root directory 
3. customized the config.toml

Result: Everything works fine, except the Icons as shown in the image.

What could be the problem here?

**Comment by fUE4** [comment]
It's missing on the demo page also:

[https://themes.gohugo.io//theme/hugo-theme-learn/en/cont/icons/](https://themes.gohugo.io//theme/hugo-theme-learn/en/cont/icons/)

**Comment by mirisbowring** [comment]
It's because they added Goldmark as default renderer in Hugo 0.60.0.  
Icons are being added via html tags in markdown.
  
You have two alternatives now:  
1. Allow unsafe in your config.toml
```toml
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
```
2. use blackfriday (the previous) as your default renderer  
```toml
[markup]
    defaultMarkdownHandler = "blackFriday"
```
  
  
see [documentation](https://gohugo.io/getting-started/configuration-markup/)
