### ISSUE TITLE
Problems with search

### ISSUE THREAD

**Issue by fgiorlando** [matcornic/hugo-theme-learn#38]
I have tried implementing search using the following method, but the search bar does not appear in the site.
I'm wondering if I'm missing a step?

-----------------------
1. install hugo-theme-learn
2. create Gruntfile.js in the root (slightly modified from https://gist.github.com/sebz/efddfc8fdcb6b480f567)

```js
var toml = require("toml");
var S = require("string");

var CONTENT_PATH_PREFIX = "content";

module.exports = function(grunt) {

    grunt.registerTask("lunr-index", function() {

        grunt.log.writeln("Build pages index");

        var indexPages = function() {
            var pagesIndex = [];
            grunt.file.recurse(CONTENT_PATH_PREFIX, function(abspath, rootdir, subdir, filename) {
                grunt.verbose.writeln("Parse file:",abspath);
                pagesIndex.push(processFile(abspath, filename));
            });

            return pagesIndex;
        };

        var processFile = function(abspath, filename) {
            var pageIndex;

            if (S(filename).endsWith(".html")) {
                pageIndex = processHTMLFile(abspath, filename);
            } else {
                pageIndex = processMDFile(abspath, filename);
            }

            return pageIndex;
        };

        var processHTMLFile = function(abspath, filename) {
            var content = grunt.file.read(abspath);
            var pageName = S(filename).chompRight(".html").s;
            var href = S(abspath)
                .chompLeft(CONTENT_PATH_PREFIX).s;
            return {
                title: pageName,
                href: href,
                content: S(content).trim().stripTags().stripPunctuation().s
            };
        };

        var processMDFile = function(abspath, filename) {
            var content = grunt.file.read(abspath);
            var pageIndex;
            // First separate the Front Matter from the content and parse it
            content = content.split("+++");
            var frontMatter;
            try {
                frontMatter = toml.parse(content[1].trim());
            } catch (e) {
                conzole.failed(e.message);
            }

            var href = S(abspath).chompLeft(CONTENT_PATH_PREFIX).chompRight(".md").s;
            }

            // Build Lunr index for this page
            pageIndex = {
                title: frontMatter.title,
                tags: frontMatter.tags,
                href: href,
                content: S(content[2]).trim().stripTags().stripPunctuation().s
            };

            return pageIndex;
        };

        grunt.file.write("static/json/search.json", JSON.stringify(indexPages()));
        grunt.log.ok("Index built");
    });
};
```

3. test that index exists in `static/json/search.json`, yes, here's an example index:
```
[{"title":"Some Chapter title","href":"/introduction/_index","content":" Chapter X Some Chapter title Lorem ipsum"},{"title":"About","href":"/introduction/about_us","content":" testing lets see if we get auto update OK"}]
```

4. enable search in `config.toml`
```toml
languageCode = "en-us"
title = "Docs"
baseurl = "https://my.url"
theme = "hugo-theme-learn"
search = "true"
```

**Comment by matcornic** [comment]
Hey @fgiorlando 

Go check this https://matcornic.github.io/hugo-learn-doc/basics/configuration/ and this https://matcornic.github.io/hugo-learn-doc/basics/installation/ 

```toml
[params]
  # Prefix URL to edit current page. Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = ""
  # Description of the site, will be used in meta information
  description = ""
  # Shows a checkmark for visited pages on the menu. Default to false
  showVisitedLinks = false
  # Automatically generates prev and next arrows
  autoNav = false
  # Activate search. Don't forget to generate the JSON index file (go check get started page)
  search = false
```

Basically, you have to:

1. Activate search by setting `search = true` parameter, but **inside** a `params` "section"  (Ex: https://github.com/matcornic/hugo-learn-doc/blob/master/config.toml#L7)
2. Generate json index. Instead of using grunt, you could use **hugo-lunr** project directly : https://matcornic.github.io/hugo-learn-doc/basics/installation/#enable-search-functionality (Ex: *index* NPM script in https://github.com/matcornic/hugo-learn-doc/blob/master/package.json)

You should find everything you need on the documentation. And if you need a real life working example, the repo is [here](https://github.com/matcornic/hugo-learn-doc).
