### ISSUE TITLE
Always show menus expanded?

### ISSUE THREAD

**Issue by MostHated** [matcornic/hugo-theme-learn#414]
Hello  
I have been trying to figure out if there is a way to always show the entire menu as expanded, not just when you are under a particular top-level, but even at the main root _index.md. Is this possible currently?

Thanks,
-MH

**Comment by macropin** [comment]
I've got a similar issue. I'm trying to prevent the second level menus from fully expanding.

**Comment by macropin** [comment]
@MostHated add the following to your custom theme and this should expand all the menus:

```css
#sidebar ul.topics ul {
  display: block;
}
``` 

For my requirements the following css will expand only the child menu one level:

```css
/*
#sidebar ul.topics > li.active ul {
    display: none;
}
#sidebar ul.topics > li.active > ul {
    display: block;
}
```

Both the above were adapted from answers given in #88
