### ISSUE TITLE
Cannot change font size

### ISSUE THREAD

**Issue by snophalhoffagus** [matcornic/hugo-theme-learn#495]
Hello! I love this theme, it's elegant and easy to work with.
However, I am unable to change the font size. I have the following in my custom theme's css:
```css
    body {
    font-family: 'Palatino';
    font-size: 1.5rem;
}
```
It takes the font-family, but not the font-size.I tried specifying it with %, px, and em as well. I also looked through past issues, including #391 to no avail.

What am I missing here?
Thanks, and sorry if this is redundant or obvious.
