### ISSUE TITLE
i18n translation by content directory

### ISSUE THREAD

**Issue by bradhuang9999** [matcornic/hugo-theme-learn#545]
Because I want to split my contents in different language into different directory

Can I set up the config.toml like the sample in [Hugo Document](https://gohugo.io/content-management/multilingual/#translation-by-content-directory) ?

```toml
[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
  [languages.fr]
    contentDir = 'content/french'
    languageName = 'Français'
    weight = 20
```
